In [3]:
import pandas as pd

# load raw data
depression_df = pd.read_csv("student_depression_dataset.csv")
performance_df = pd.read_csv("student_performance.csv")

# standardize column names
depression_df.columns = depression_df.columns.str.lower().str.replace(" ", "_")
performance_df.columns = performance_df.columns.str.lower().str.replace(" ", "_")

# handle missing values
depression_df.fillna(depression_df.median(numeric_only=True), inplace=True)
performance_df.fillna(performance_df.median(numeric_only=True), inplace=True)

# save cleaned versions
depression_df.to_csv("cleaned_depression.csv", index=False)
performance_df.to_csv("cleaned_performance.csv", index=False)

In [9]:
# preview
print(depression_df.shape)
depression_df.head()

(27901, 18)

,id,gender,age,city,profession,academic_pressure,work_pressure,cgpa,study_satisfaction,job_satisfaction,sleep_duration,dietary_habits,degree,have_you_ever_had_suicidal_thoughts_?,work/study_hours,financial_stress,family_history_of_mental_illness,depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0

In [10]:
# preview
print(performance_df.shape)
performance_df.head()

(5000, 23)

,student_id,first_name,last_name,email,gender,age,department,attendance_(%),midterm_score,final_score,...,projects_score,total_score,grade,study_hours_per_week,extracurricular_activities,internet_access_at_home,parent_education_level,family_income_level,stress_level_(1-10),sleep_hours_per_night
0,S1000,Omar,Williams,student0@university.com,Female,22,Mathematics,97.36,40.61,59.61,...,62.84,83.49,C,10.3,Yes,No,Master's,Medium,1,5.9
1,S1001,Maria,Brown,student1@university.com,Male,18,Business,97.71,57.27,74.00,...,98.23,92.29,F,27.1,No,No,High School,Low,4,4.3
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Engineering,99.52,41.84,63.85,...,91.22,93.55,F,12.4,Yes,No,High School,Low,9,6.1
3,S1003,Omar,Williams,student3@university.com,Female,24,Engineering,90.38,45.65,44.44,...,55.48,51.03,A,25.5,No,Yes,High School,Low,8,4.9
4,S1004,John,Smith,student4@university.com,Female,23,CS,59.41,53.13,61.77,...,87.43,90.91,A,13.3,Yes,No,Master's,Medium,6,4.5